name: Deploy Affirmations API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0
    
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    
    - name: Test API
      run: |
        ruby app.rb &
        sleep 5
        curl -f http://localhost:4567/health || exit 1
        pkill -f "ruby app.rb"
    
    - name: Deploy to Render
      if: github.ref == 'refs/heads/master'
      run: |
        echo "API is ready for deployment!"
        echo "Manual deployment steps:"
        echo "1. Go to https://render.com"
        echo "2. Connect your GitHub repository"
        echo "3. Create new Web Service"
        echo "4. Build Command: bundle install"
        echo "5. Start Command: ruby app.rb"
