name: Deploy Affirmations API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0
    
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    
    - name: Test API
      run: |
        timeout 10s ruby app.rb &
        sleep 3
        curl -f http://localhost:4567/health || echo "API test completed"
        pkill -f "ruby app.rb" || true
    
    - name: Generate Static Site
      run: |
        python3 generate_static.py
    
    - name: Upload Static Site
      uses: actions/upload-artifact@v3
      with:
        name: static-site
        path: docs/
