name: Ultra Simple Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Generate Static Site
      run: |
        python3 generate_static.py
        echo "Files generated:"
        ls -la docs/
    
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: static-files
        path: docs/
